//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.CustomerReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Rentalinformation", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Rentalinformation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        private int HowManyDaysField;
        
        private int StartKmField;
        
        private int LastKmField;
        
        private int PaymentField;
        
        private bool IsActiveField;
        
        private int VehicleIDField;
        
        private int CustomerIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int HowManyDays {
            get {
                return this.HowManyDaysField;
            }
            set {
                if ((this.HowManyDaysField.Equals(value) != true)) {
                    this.HowManyDaysField = value;
                    this.RaisePropertyChanged("HowManyDays");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int StartKm {
            get {
                return this.StartKmField;
            }
            set {
                if ((this.StartKmField.Equals(value) != true)) {
                    this.StartKmField = value;
                    this.RaisePropertyChanged("StartKm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int LastKm {
            get {
                return this.LastKmField;
            }
            set {
                if ((this.LastKmField.Equals(value) != true)) {
                    this.LastKmField = value;
                    this.RaisePropertyChanged("LastKm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int Payment {
            get {
                return this.PaymentField;
            }
            set {
                if ((this.PaymentField.Equals(value) != true)) {
                    this.PaymentField = value;
                    this.RaisePropertyChanged("Payment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public bool IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int VehicleID {
            get {
                return this.VehicleIDField;
            }
            set {
                if ((this.VehicleIDField.Equals(value) != true)) {
                    this.VehicleIDField = value;
                    this.RaisePropertyChanged("VehicleID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int CustomerID {
            get {
                return this.CustomerIDField;
            }
            set {
                if ((this.CustomerIDField.Equals(value) != true)) {
                    this.CustomerIDField = value;
                    this.RaisePropertyChanged("CustomerID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Customer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        private System.Nullable<System.DateTime> BirthDateField;
        
        private int TCNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<System.DateTime> BirthDate {
            get {
                return this.BirthDateField;
            }
            set {
                if ((this.BirthDateField.Equals(value) != true)) {
                    this.BirthDateField = value;
                    this.RaisePropertyChanged("BirthDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int TCNumber {
            get {
                return this.TCNumberField;
            }
            set {
                if ((this.TCNumberField.Equals(value) != true)) {
                    this.TCNumberField = value;
                    this.RaisePropertyChanged("TCNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CustomerReference.CustomerServiceSoap")]
    public interface CustomerServiceSoap {
        
        // CODEGEN: Generating message contract since element name RentRequestResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RentRequest", ReplyAction="*")]
        Web.CustomerReference.RentRequestResponse RentRequest(Web.CustomerReference.RentRequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RentRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<Web.CustomerReference.RentRequestResponse> RentRequestAsync(Web.CustomerReference.RentRequestRequest request);
        
        // CODEGEN: Generating message contract since element name customer from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        Web.CustomerReference.AddResponse Add(Web.CustomerReference.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        System.Threading.Tasks.Task<Web.CustomerReference.AddResponse> AddAsync(Web.CustomerReference.AddRequest request);
        
        // CODEGEN: Generating message contract since element name GetResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get", ReplyAction="*")]
        Web.CustomerReference.GetResponse Get(Web.CustomerReference.GetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get", ReplyAction="*")]
        System.Threading.Tasks.Task<Web.CustomerReference.GetResponse> GetAsync(Web.CustomerReference.GetRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RentRequestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RentRequest", Namespace="http://tempuri.org/", Order=0)]
        public Web.CustomerReference.RentRequestRequestBody Body;
        
        public RentRequestRequest() {
        }
        
        public RentRequestRequest(Web.CustomerReference.RentRequestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RentRequestRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int TCNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int vehicleId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int howManyDays;
        
        public RentRequestRequestBody() {
        }
        
        public RentRequestRequestBody(int TCNumber, int vehicleId, int howManyDays) {
            this.TCNumber = TCNumber;
            this.vehicleId = vehicleId;
            this.howManyDays = howManyDays;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RentRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RentRequestResponse", Namespace="http://tempuri.org/", Order=0)]
        public Web.CustomerReference.RentRequestResponseBody Body;
        
        public RentRequestResponse() {
        }
        
        public RentRequestResponse(Web.CustomerReference.RentRequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RentRequestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Web.CustomerReference.Rentalinformation RentRequestResult;
        
        public RentRequestResponseBody() {
        }
        
        public RentRequestResponseBody(Web.CustomerReference.Rentalinformation RentRequestResult) {
            this.RentRequestResult = RentRequestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Add", Namespace="http://tempuri.org/", Order=0)]
        public Web.CustomerReference.AddRequestBody Body;
        
        public AddRequest() {
        }
        
        public AddRequest(Web.CustomerReference.AddRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Web.CustomerReference.Customer customer;
        
        public AddRequestBody() {
        }
        
        public AddRequestBody(Web.CustomerReference.Customer customer) {
            this.customer = customer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddResponse", Namespace="http://tempuri.org/", Order=0)]
        public Web.CustomerReference.AddResponseBody Body;
        
        public AddResponse() {
        }
        
        public AddResponse(Web.CustomerReference.AddResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddResponseBody {
        
        public AddResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get", Namespace="http://tempuri.org/", Order=0)]
        public Web.CustomerReference.GetRequestBody Body;
        
        public GetRequest() {
        }
        
        public GetRequest(Web.CustomerReference.GetRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int customerId;
        
        public GetRequestBody() {
        }
        
        public GetRequestBody(int customerId) {
            this.customerId = customerId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetResponse", Namespace="http://tempuri.org/", Order=0)]
        public Web.CustomerReference.GetResponseBody Body;
        
        public GetResponse() {
        }
        
        public GetResponse(Web.CustomerReference.GetResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Web.CustomerReference.Customer GetResult;
        
        public GetResponseBody() {
        }
        
        public GetResponseBody(Web.CustomerReference.Customer GetResult) {
            this.GetResult = GetResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CustomerServiceSoapChannel : Web.CustomerReference.CustomerServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomerServiceSoapClient : System.ServiceModel.ClientBase<Web.CustomerReference.CustomerServiceSoap>, Web.CustomerReference.CustomerServiceSoap {
        
        public CustomerServiceSoapClient() {
        }
        
        public CustomerServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomerServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Web.CustomerReference.RentRequestResponse Web.CustomerReference.CustomerServiceSoap.RentRequest(Web.CustomerReference.RentRequestRequest request) {
            return base.Channel.RentRequest(request);
        }
        
        public Web.CustomerReference.Rentalinformation RentRequest(int TCNumber, int vehicleId, int howManyDays) {
            Web.CustomerReference.RentRequestRequest inValue = new Web.CustomerReference.RentRequestRequest();
            inValue.Body = new Web.CustomerReference.RentRequestRequestBody();
            inValue.Body.TCNumber = TCNumber;
            inValue.Body.vehicleId = vehicleId;
            inValue.Body.howManyDays = howManyDays;
            Web.CustomerReference.RentRequestResponse retVal = ((Web.CustomerReference.CustomerServiceSoap)(this)).RentRequest(inValue);
            return retVal.Body.RentRequestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Web.CustomerReference.RentRequestResponse> Web.CustomerReference.CustomerServiceSoap.RentRequestAsync(Web.CustomerReference.RentRequestRequest request) {
            return base.Channel.RentRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<Web.CustomerReference.RentRequestResponse> RentRequestAsync(int TCNumber, int vehicleId, int howManyDays) {
            Web.CustomerReference.RentRequestRequest inValue = new Web.CustomerReference.RentRequestRequest();
            inValue.Body = new Web.CustomerReference.RentRequestRequestBody();
            inValue.Body.TCNumber = TCNumber;
            inValue.Body.vehicleId = vehicleId;
            inValue.Body.howManyDays = howManyDays;
            return ((Web.CustomerReference.CustomerServiceSoap)(this)).RentRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Web.CustomerReference.AddResponse Web.CustomerReference.CustomerServiceSoap.Add(Web.CustomerReference.AddRequest request) {
            return base.Channel.Add(request);
        }
        
        public void Add(Web.CustomerReference.Customer customer) {
            Web.CustomerReference.AddRequest inValue = new Web.CustomerReference.AddRequest();
            inValue.Body = new Web.CustomerReference.AddRequestBody();
            inValue.Body.customer = customer;
            Web.CustomerReference.AddResponse retVal = ((Web.CustomerReference.CustomerServiceSoap)(this)).Add(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Web.CustomerReference.AddResponse> Web.CustomerReference.CustomerServiceSoap.AddAsync(Web.CustomerReference.AddRequest request) {
            return base.Channel.AddAsync(request);
        }
        
        public System.Threading.Tasks.Task<Web.CustomerReference.AddResponse> AddAsync(Web.CustomerReference.Customer customer) {
            Web.CustomerReference.AddRequest inValue = new Web.CustomerReference.AddRequest();
            inValue.Body = new Web.CustomerReference.AddRequestBody();
            inValue.Body.customer = customer;
            return ((Web.CustomerReference.CustomerServiceSoap)(this)).AddAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Web.CustomerReference.GetResponse Web.CustomerReference.CustomerServiceSoap.Get(Web.CustomerReference.GetRequest request) {
            return base.Channel.Get(request);
        }
        
        public Web.CustomerReference.Customer Get(int customerId) {
            Web.CustomerReference.GetRequest inValue = new Web.CustomerReference.GetRequest();
            inValue.Body = new Web.CustomerReference.GetRequestBody();
            inValue.Body.customerId = customerId;
            Web.CustomerReference.GetResponse retVal = ((Web.CustomerReference.CustomerServiceSoap)(this)).Get(inValue);
            return retVal.Body.GetResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Web.CustomerReference.GetResponse> Web.CustomerReference.CustomerServiceSoap.GetAsync(Web.CustomerReference.GetRequest request) {
            return base.Channel.GetAsync(request);
        }
        
        public System.Threading.Tasks.Task<Web.CustomerReference.GetResponse> GetAsync(int customerId) {
            Web.CustomerReference.GetRequest inValue = new Web.CustomerReference.GetRequest();
            inValue.Body = new Web.CustomerReference.GetRequestBody();
            inValue.Body.customerId = customerId;
            return ((Web.CustomerReference.CustomerServiceSoap)(this)).GetAsync(inValue);
        }
    }
}
