//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.VehicleReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VehicleInformation", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class VehicleInformation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        private int MinLicenseAgeField;
        
        private int MinAgeField;
        
        private int DailyBorderKmField;
        
        private bool AirbagField;
        
        private int BaggageVolumeField;
        
        private int SeatingCapacityField;
        
        private int DailyRentalPriceField;
        
        private int CompanyIDField;
        
        private int CustomerIDField;
        
        private bool isRentaledField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Model {
            get {
                return this.ModelField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelField, value) != true)) {
                    this.ModelField = value;
                    this.RaisePropertyChanged("Model");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int MinLicenseAge {
            get {
                return this.MinLicenseAgeField;
            }
            set {
                if ((this.MinLicenseAgeField.Equals(value) != true)) {
                    this.MinLicenseAgeField = value;
                    this.RaisePropertyChanged("MinLicenseAge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int MinAge {
            get {
                return this.MinAgeField;
            }
            set {
                if ((this.MinAgeField.Equals(value) != true)) {
                    this.MinAgeField = value;
                    this.RaisePropertyChanged("MinAge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int DailyBorderKm {
            get {
                return this.DailyBorderKmField;
            }
            set {
                if ((this.DailyBorderKmField.Equals(value) != true)) {
                    this.DailyBorderKmField = value;
                    this.RaisePropertyChanged("DailyBorderKm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public bool Airbag {
            get {
                return this.AirbagField;
            }
            set {
                if ((this.AirbagField.Equals(value) != true)) {
                    this.AirbagField = value;
                    this.RaisePropertyChanged("Airbag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int BaggageVolume {
            get {
                return this.BaggageVolumeField;
            }
            set {
                if ((this.BaggageVolumeField.Equals(value) != true)) {
                    this.BaggageVolumeField = value;
                    this.RaisePropertyChanged("BaggageVolume");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public int SeatingCapacity {
            get {
                return this.SeatingCapacityField;
            }
            set {
                if ((this.SeatingCapacityField.Equals(value) != true)) {
                    this.SeatingCapacityField = value;
                    this.RaisePropertyChanged("SeatingCapacity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public int DailyRentalPrice {
            get {
                return this.DailyRentalPriceField;
            }
            set {
                if ((this.DailyRentalPriceField.Equals(value) != true)) {
                    this.DailyRentalPriceField = value;
                    this.RaisePropertyChanged("DailyRentalPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public int CompanyID {
            get {
                return this.CompanyIDField;
            }
            set {
                if ((this.CompanyIDField.Equals(value) != true)) {
                    this.CompanyIDField = value;
                    this.RaisePropertyChanged("CompanyID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public int CustomerID {
            get {
                return this.CustomerIDField;
            }
            set {
                if ((this.CustomerIDField.Equals(value) != true)) {
                    this.CustomerIDField = value;
                    this.RaisePropertyChanged("CustomerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public bool isRentaled {
            get {
                return this.isRentaledField;
            }
            set {
                if ((this.isRentaledField.Equals(value) != true)) {
                    this.isRentaledField = value;
                    this.RaisePropertyChanged("isRentaled");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Rentalinformation", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Rentalinformation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        private int HowManyDaysField;
        
        private int StartKmField;
        
        private int LastKmField;
        
        private int PaymentField;
        
        private bool IsActiveField;
        
        private int VehicleIDField;
        
        private int CustomerIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int HowManyDays {
            get {
                return this.HowManyDaysField;
            }
            set {
                if ((this.HowManyDaysField.Equals(value) != true)) {
                    this.HowManyDaysField = value;
                    this.RaisePropertyChanged("HowManyDays");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int StartKm {
            get {
                return this.StartKmField;
            }
            set {
                if ((this.StartKmField.Equals(value) != true)) {
                    this.StartKmField = value;
                    this.RaisePropertyChanged("StartKm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int LastKm {
            get {
                return this.LastKmField;
            }
            set {
                if ((this.LastKmField.Equals(value) != true)) {
                    this.LastKmField = value;
                    this.RaisePropertyChanged("LastKm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int Payment {
            get {
                return this.PaymentField;
            }
            set {
                if ((this.PaymentField.Equals(value) != true)) {
                    this.PaymentField = value;
                    this.RaisePropertyChanged("Payment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public bool IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int VehicleID {
            get {
                return this.VehicleIDField;
            }
            set {
                if ((this.VehicleIDField.Equals(value) != true)) {
                    this.VehicleIDField = value;
                    this.RaisePropertyChanged("VehicleID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int CustomerID {
            get {
                return this.CustomerIDField;
            }
            set {
                if ((this.CustomerIDField.Equals(value) != true)) {
                    this.CustomerIDField = value;
                    this.RaisePropertyChanged("CustomerID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VehicleReference.VehicleServiceServiceSoap")]
    public interface VehicleServiceServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetAllResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAll", ReplyAction="*")]
        Web.VehicleReference.GetAllResponse GetAll(Web.VehicleReference.GetAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAll", ReplyAction="*")]
        System.Threading.Tasks.Task<Web.VehicleReference.GetAllResponse> GetAllAsync(Web.VehicleReference.GetAllRequest request);
        
        // CODEGEN: Generating message contract since element name GetRentaledVehiclesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRentaledVehicles", ReplyAction="*")]
        Web.VehicleReference.GetRentaledVehiclesResponse GetRentaledVehicles(Web.VehicleReference.GetRentaledVehiclesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRentaledVehicles", ReplyAction="*")]
        System.Threading.Tasks.Task<Web.VehicleReference.GetRentaledVehiclesResponse> GetRentaledVehiclesAsync(Web.VehicleReference.GetRentaledVehiclesRequest request);
        
        // CODEGEN: Generating message contract since element name GetResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get", ReplyAction="*")]
        Web.VehicleReference.GetResponse Get(Web.VehicleReference.GetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get", ReplyAction="*")]
        System.Threading.Tasks.Task<Web.VehicleReference.GetResponse> GetAsync(Web.VehicleReference.GetRequest request);
        
        // CODEGEN: Generating message contract since element name rental from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RentACar", ReplyAction="*")]
        Web.VehicleReference.RentACarResponse RentACar(Web.VehicleReference.RentACarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RentACar", ReplyAction="*")]
        System.Threading.Tasks.Task<Web.VehicleReference.RentACarResponse> RentACarAsync(Web.VehicleReference.RentACarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UnRentACar", ReplyAction="*")]
        bool UnRentACar(int vehicleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UnRentACar", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> UnRentACarAsync(int vehicleId);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAll", Namespace="http://tempuri.org/", Order=0)]
        public Web.VehicleReference.GetAllRequestBody Body;
        
        public GetAllRequest() {
        }
        
        public GetAllRequest(Web.VehicleReference.GetAllRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllRequestBody {
        
        public GetAllRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllResponse", Namespace="http://tempuri.org/", Order=0)]
        public Web.VehicleReference.GetAllResponseBody Body;
        
        public GetAllResponse() {
        }
        
        public GetAllResponse(Web.VehicleReference.GetAllResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Web.VehicleReference.VehicleInformation[] GetAllResult;
        
        public GetAllResponseBody() {
        }
        
        public GetAllResponseBody(Web.VehicleReference.VehicleInformation[] GetAllResult) {
            this.GetAllResult = GetAllResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRentaledVehiclesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRentaledVehicles", Namespace="http://tempuri.org/", Order=0)]
        public Web.VehicleReference.GetRentaledVehiclesRequestBody Body;
        
        public GetRentaledVehiclesRequest() {
        }
        
        public GetRentaledVehiclesRequest(Web.VehicleReference.GetRentaledVehiclesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetRentaledVehiclesRequestBody {
        
        public GetRentaledVehiclesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRentaledVehiclesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRentaledVehiclesResponse", Namespace="http://tempuri.org/", Order=0)]
        public Web.VehicleReference.GetRentaledVehiclesResponseBody Body;
        
        public GetRentaledVehiclesResponse() {
        }
        
        public GetRentaledVehiclesResponse(Web.VehicleReference.GetRentaledVehiclesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRentaledVehiclesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Web.VehicleReference.VehicleInformation[] GetRentaledVehiclesResult;
        
        public GetRentaledVehiclesResponseBody() {
        }
        
        public GetRentaledVehiclesResponseBody(Web.VehicleReference.VehicleInformation[] GetRentaledVehiclesResult) {
            this.GetRentaledVehiclesResult = GetRentaledVehiclesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get", Namespace="http://tempuri.org/", Order=0)]
        public Web.VehicleReference.GetRequestBody Body;
        
        public GetRequest() {
        }
        
        public GetRequest(Web.VehicleReference.GetRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int vehicleId;
        
        public GetRequestBody() {
        }
        
        public GetRequestBody(int vehicleId) {
            this.vehicleId = vehicleId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetResponse", Namespace="http://tempuri.org/", Order=0)]
        public Web.VehicleReference.GetResponseBody Body;
        
        public GetResponse() {
        }
        
        public GetResponse(Web.VehicleReference.GetResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Web.VehicleReference.VehicleInformation GetResult;
        
        public GetResponseBody() {
        }
        
        public GetResponseBody(Web.VehicleReference.VehicleInformation GetResult) {
            this.GetResult = GetResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RentACarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RentACar", Namespace="http://tempuri.org/", Order=0)]
        public Web.VehicleReference.RentACarRequestBody Body;
        
        public RentACarRequest() {
        }
        
        public RentACarRequest(Web.VehicleReference.RentACarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RentACarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int vehicleId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int customerId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Web.VehicleReference.Rentalinformation rental;
        
        public RentACarRequestBody() {
        }
        
        public RentACarRequestBody(int vehicleId, int customerId, Web.VehicleReference.Rentalinformation rental) {
            this.vehicleId = vehicleId;
            this.customerId = customerId;
            this.rental = rental;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RentACarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RentACarResponse", Namespace="http://tempuri.org/", Order=0)]
        public Web.VehicleReference.RentACarResponseBody Body;
        
        public RentACarResponse() {
        }
        
        public RentACarResponse(Web.VehicleReference.RentACarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RentACarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool RentACarResult;
        
        public RentACarResponseBody() {
        }
        
        public RentACarResponseBody(bool RentACarResult) {
            this.RentACarResult = RentACarResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface VehicleServiceServiceSoapChannel : Web.VehicleReference.VehicleServiceServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VehicleServiceServiceSoapClient : System.ServiceModel.ClientBase<Web.VehicleReference.VehicleServiceServiceSoap>, Web.VehicleReference.VehicleServiceServiceSoap {
        
        public VehicleServiceServiceSoapClient() {
        }
        
        public VehicleServiceServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VehicleServiceServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VehicleServiceServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VehicleServiceServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Web.VehicleReference.GetAllResponse Web.VehicleReference.VehicleServiceServiceSoap.GetAll(Web.VehicleReference.GetAllRequest request) {
            return base.Channel.GetAll(request);
        }
        
        public Web.VehicleReference.VehicleInformation[] GetAll() {
            Web.VehicleReference.GetAllRequest inValue = new Web.VehicleReference.GetAllRequest();
            inValue.Body = new Web.VehicleReference.GetAllRequestBody();
            Web.VehicleReference.GetAllResponse retVal = ((Web.VehicleReference.VehicleServiceServiceSoap)(this)).GetAll(inValue);
            return retVal.Body.GetAllResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Web.VehicleReference.GetAllResponse> Web.VehicleReference.VehicleServiceServiceSoap.GetAllAsync(Web.VehicleReference.GetAllRequest request) {
            return base.Channel.GetAllAsync(request);
        }
        
        public System.Threading.Tasks.Task<Web.VehicleReference.GetAllResponse> GetAllAsync() {
            Web.VehicleReference.GetAllRequest inValue = new Web.VehicleReference.GetAllRequest();
            inValue.Body = new Web.VehicleReference.GetAllRequestBody();
            return ((Web.VehicleReference.VehicleServiceServiceSoap)(this)).GetAllAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Web.VehicleReference.GetRentaledVehiclesResponse Web.VehicleReference.VehicleServiceServiceSoap.GetRentaledVehicles(Web.VehicleReference.GetRentaledVehiclesRequest request) {
            return base.Channel.GetRentaledVehicles(request);
        }
        
        public Web.VehicleReference.VehicleInformation[] GetRentaledVehicles() {
            Web.VehicleReference.GetRentaledVehiclesRequest inValue = new Web.VehicleReference.GetRentaledVehiclesRequest();
            inValue.Body = new Web.VehicleReference.GetRentaledVehiclesRequestBody();
            Web.VehicleReference.GetRentaledVehiclesResponse retVal = ((Web.VehicleReference.VehicleServiceServiceSoap)(this)).GetRentaledVehicles(inValue);
            return retVal.Body.GetRentaledVehiclesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Web.VehicleReference.GetRentaledVehiclesResponse> Web.VehicleReference.VehicleServiceServiceSoap.GetRentaledVehiclesAsync(Web.VehicleReference.GetRentaledVehiclesRequest request) {
            return base.Channel.GetRentaledVehiclesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Web.VehicleReference.GetRentaledVehiclesResponse> GetRentaledVehiclesAsync() {
            Web.VehicleReference.GetRentaledVehiclesRequest inValue = new Web.VehicleReference.GetRentaledVehiclesRequest();
            inValue.Body = new Web.VehicleReference.GetRentaledVehiclesRequestBody();
            return ((Web.VehicleReference.VehicleServiceServiceSoap)(this)).GetRentaledVehiclesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Web.VehicleReference.GetResponse Web.VehicleReference.VehicleServiceServiceSoap.Get(Web.VehicleReference.GetRequest request) {
            return base.Channel.Get(request);
        }
        
        public Web.VehicleReference.VehicleInformation Get(int vehicleId) {
            Web.VehicleReference.GetRequest inValue = new Web.VehicleReference.GetRequest();
            inValue.Body = new Web.VehicleReference.GetRequestBody();
            inValue.Body.vehicleId = vehicleId;
            Web.VehicleReference.GetResponse retVal = ((Web.VehicleReference.VehicleServiceServiceSoap)(this)).Get(inValue);
            return retVal.Body.GetResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Web.VehicleReference.GetResponse> Web.VehicleReference.VehicleServiceServiceSoap.GetAsync(Web.VehicleReference.GetRequest request) {
            return base.Channel.GetAsync(request);
        }
        
        public System.Threading.Tasks.Task<Web.VehicleReference.GetResponse> GetAsync(int vehicleId) {
            Web.VehicleReference.GetRequest inValue = new Web.VehicleReference.GetRequest();
            inValue.Body = new Web.VehicleReference.GetRequestBody();
            inValue.Body.vehicleId = vehicleId;
            return ((Web.VehicleReference.VehicleServiceServiceSoap)(this)).GetAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Web.VehicleReference.RentACarResponse Web.VehicleReference.VehicleServiceServiceSoap.RentACar(Web.VehicleReference.RentACarRequest request) {
            return base.Channel.RentACar(request);
        }
        
        public bool RentACar(int vehicleId, int customerId, Web.VehicleReference.Rentalinformation rental) {
            Web.VehicleReference.RentACarRequest inValue = new Web.VehicleReference.RentACarRequest();
            inValue.Body = new Web.VehicleReference.RentACarRequestBody();
            inValue.Body.vehicleId = vehicleId;
            inValue.Body.customerId = customerId;
            inValue.Body.rental = rental;
            Web.VehicleReference.RentACarResponse retVal = ((Web.VehicleReference.VehicleServiceServiceSoap)(this)).RentACar(inValue);
            return retVal.Body.RentACarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Web.VehicleReference.RentACarResponse> Web.VehicleReference.VehicleServiceServiceSoap.RentACarAsync(Web.VehicleReference.RentACarRequest request) {
            return base.Channel.RentACarAsync(request);
        }
        
        public System.Threading.Tasks.Task<Web.VehicleReference.RentACarResponse> RentACarAsync(int vehicleId, int customerId, Web.VehicleReference.Rentalinformation rental) {
            Web.VehicleReference.RentACarRequest inValue = new Web.VehicleReference.RentACarRequest();
            inValue.Body = new Web.VehicleReference.RentACarRequestBody();
            inValue.Body.vehicleId = vehicleId;
            inValue.Body.customerId = customerId;
            inValue.Body.rental = rental;
            return ((Web.VehicleReference.VehicleServiceServiceSoap)(this)).RentACarAsync(inValue);
        }
        
        public bool UnRentACar(int vehicleId) {
            return base.Channel.UnRentACar(vehicleId);
        }
        
        public System.Threading.Tasks.Task<bool> UnRentACarAsync(int vehicleId) {
            return base.Channel.UnRentACarAsync(vehicleId);
        }
    }
}
